import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/api/generate-question")({
  server: {
    handlers: {
      GET: async () => {
        try {
          const apiKey = process.env.GROQ_API_KEY || process.env.TUTOR_API_KEY || process.env.OPENAI_API_KEY;
          if (!apiKey) {
            throw new Error("No API key configured on server.");
          }

          const baseUrl = process.env.TUTOR_BASE_URL || "https://api.groq.com/openai/v1/chat/completions";
          const model = process.env.TUTOR_MODEL || "llama-3.1-8b-instant";

          const systemInstruction = `You are a dynamic educational AI generator for a STEM platform.
Your job is to generate exactly ONE very hard and challenging Multiple Choice Question (MCQ) in one of these categories:
- General Knowledge (GK) - focus on scientific breakthroughs, history of science, geography, or history.
- Current Affairs - recent technological or scientific events (up to 2024/2026).
- Advanced STEM - challenging math, physics, chemistry, or programming/algorithm questions.

The question MUST be hard, intelligent, and highly engaging. Do not generate simple or repetitive questions.
You must provide exactly 4 options labeled A, B, C, D.
Respond EXACTLY in valid JSON format:
{
  "q": "The detailed hard question text",
  "options": [
    "Option A text",
    "Option B text",
    "Option C text",
    "Option D text"
  ],
  "a": "A" or "B" or "C" or "D" (must be the single letter corresponding to the correct option)
}`;

          const resp = await fetch(baseUrl, {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${apiKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model,
              messages: [
                { role: "system", content: systemInstruction },
                { role: "user", content: "Generate one hard MCQ question." }
              ],
              response_format: { type: "json_object" },
              temperature: 0.85,
              max_tokens: 350
            }),
          });

          if (!resp.ok) {
            throw new Error(`Groq API returned error status: ${resp.status}`);
          }

          const data = await resp.json();
          const content = data.choices[0].message.content;
          const result = JSON.parse(content);

          // Verify structure
          if (!result.q || !Array.isArray(result.options) || result.options.length !== 4 || !result.a) {
            throw new Error("Invalid question structure generated by LLM.");
          }

          return new Response(JSON.stringify(result), {
            status: 200,
            headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
          });

        } catch (e: any) {
          console.error("AI Question Generation Exception:", e);
          
          // Failure fallbacks (high-quality hard GK, STEM, and current affairs MCQ)
          const fallbacks = [
            {
              q: "Which major space mission in late 2022 successfully demonstrated the kinetic impact technique by changing the orbit of the asteroid moonlet Dimorphos?",
              options: [
                "NASA's OSIRIS-REx mission",
                "NASA's DART (Double Asteroid Redirection Test)",
                "JAXA's Hayabusa2 mission",
                "ESA's Rosetta mission"
              ],
              a: "B"
            },
            {
              q: "Who was awarded the 2024 Nobel Prize in Physics for foundational discoveries and inventions that enable machine learning with artificial neural networks?",
              options: [
                "John J. Hopfield and Geoffrey E. Hinton",
                "Syukuro Manabe and Klaus Hasselmann",
                "Alain Aspect and Anton Zeilinger",
                "Pierre Agostini and Anne L'Huillier"
              ],
              a: "A"
            },
            {
              q: "In computability theory, what is the complexity class of problems that can be solved by a deterministic Turing machine in time O(2^(p(n))) where p(n) is a polynomial?",
              options: [
                "P",
                "NP",
                "EXPTIME",
                "PSPACE"
              ],
              a: "C"
            },
            {
              q: "What is the primary organic product of the reaction between an alkene and ozone followed by zinc and water (ozonolysis)?",
              options: [
                "Carboxylic acid",
                "Aldehyde or Ketone",
                "Epoxide",
                "Diol"
              ],
              a: "B"
            },
            {
              q: "Which state of matter is primarily composed of highly ionized gas containing approximately equal numbers of positive ions and electrons, exhibiting collective behavior?",
              options: [
                "Superfluid",
                "Plasma",
                "Bose-Einstein Condensate",
                "Quark-Gluon Plasma"
              ],
              a: "B"
            }
          ];

          const selected = fallbacks[Math.floor(Math.random() * fallbacks.length)];
          return new Response(JSON.stringify(selected), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
  },
});
