/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as LabRouteImport } from './routes/lab'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiQuizRouteImport } from './routes/api/quiz'
import { Route as ApiModerateChatRouteImport } from './routes/api/moderate-chat'
import { Route as ApiGenerateQuestionRouteImport } from './routes/api/generate-question'
import { Route as ApiGeneratePathRouteImport } from './routes/api/generate-path'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizRoute = ApiQuizRouteImport.update({
  id: '/api/quiz',
  path: '/api/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModerateChatRoute = ApiModerateChatRouteImport.update({
  id: '/api/moderate-chat',
  path: '/api/moderate-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateQuestionRoute = ApiGenerateQuestionRouteImport.update({
  id: '/api/generate-question',
  path: '/api/generate-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePathRoute = ApiGeneratePathRouteImport.update({
  id: '/api/generate-path',
  path: '/api/generate-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/dashboard': typeof DashboardRoute
  '/garden': typeof GardenRoute
  '/lab': typeof LabRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-path': typeof ApiGeneratePathRoute
  '/api/generate-question': typeof ApiGenerateQuestionRoute
  '/api/moderate-chat': typeof ApiModerateChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/speak': typeof ApiSpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/dashboard': typeof DashboardRoute
  '/garden': typeof GardenRoute
  '/lab': typeof LabRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-path': typeof ApiGeneratePathRoute
  '/api/generate-question': typeof ApiGenerateQuestionRoute
  '/api/moderate-chat': typeof ApiModerateChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/speak': typeof ApiSpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/dashboard': typeof DashboardRoute
  '/garden': typeof GardenRoute
  '/lab': typeof LabRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-path': typeof ApiGeneratePathRoute
  '/api/generate-question': typeof ApiGenerateQuestionRoute
  '/api/moderate-chat': typeof ApiModerateChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/speak': typeof ApiSpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/dashboard'
    | '/garden'
    | '/lab'
    | '/paths'
    | '/quiz'
    | '/shop'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/tutor'
    | '/api/chat'
    | '/api/generate-path'
    | '/api/generate-question'
    | '/api/moderate-chat'
    | '/api/quiz'
    | '/api/speak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/dashboard'
    | '/garden'
    | '/lab'
    | '/paths'
    | '/quiz'
    | '/shop'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/tutor'
    | '/api/chat'
    | '/api/generate-path'
    | '/api/generate-question'
    | '/api/moderate-chat'
    | '/api/quiz'
    | '/api/speak'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/dashboard'
    | '/garden'
    | '/lab'
    | '/paths'
    | '/quiz'
    | '/shop'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/tutor'
    | '/api/chat'
    | '/api/generate-path'
    | '/api/generate-question'
    | '/api/moderate-chat'
    | '/api/quiz'
    | '/api/speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  DashboardRoute: typeof DashboardRoute
  GardenRoute: typeof GardenRoute
  LabRoute: typeof LabRoute
  PathsRoute: typeof PathsRoute
  QuizRoute: typeof QuizRoute
  ShopRoute: typeof ShopRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorRoute: typeof TutorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGeneratePathRoute: typeof ApiGeneratePathRoute
  ApiGenerateQuestionRoute: typeof ApiGenerateQuestionRoute
  ApiModerateChatRoute: typeof ApiModerateChatRoute
  ApiQuizRoute: typeof ApiQuizRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz': {
      id: '/api/quiz'
      path: '/api/quiz'
      fullPath: '/api/quiz'
      preLoaderRoute: typeof ApiQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moderate-chat': {
      id: '/api/moderate-chat'
      path: '/api/moderate-chat'
      fullPath: '/api/moderate-chat'
      preLoaderRoute: typeof ApiModerateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-question': {
      id: '/api/generate-question'
      path: '/api/generate-question'
      fullPath: '/api/generate-question'
      preLoaderRoute: typeof ApiGenerateQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-path': {
      id: '/api/generate-path'
      path: '/api/generate-path'
      fullPath: '/api/generate-path'
      preLoaderRoute: typeof ApiGeneratePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  DashboardRoute: DashboardRoute,
  GardenRoute: GardenRoute,
  LabRoute: LabRoute,
  PathsRoute: PathsRoute,
  QuizRoute: QuizRoute,
  ShopRoute: ShopRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorRoute: TutorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGeneratePathRoute: ApiGeneratePathRoute,
  ApiGenerateQuestionRoute: ApiGenerateQuestionRoute,
  ApiModerateChatRoute: ApiModerateChatRoute,
  ApiQuizRoute: ApiQuizRoute,
  ApiSpeakRoute: ApiSpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
